-- VERIFICAR QUE PARES DEL MODELO NO QUEDARON EN LA BASE
-- Ejecutar:
--   docker cp verificar_pares.sql reposteria-db:/tmp/
--   docker exec -i reposteria-db psql -U bruno -d reposteria_db -f /tmp/verificar_pares.sql
-- No modifica nada: solo consulta.

-- A) Pares del archivo que NO estan en la base (esperado si todo calza: 0 rows)
WITH esperado(o, s) AS (VALUES
  ('aceite de coco','aceite vegetal'),
  ('aceite de coco','manteca vegetal'),
  ('aceite de coco','aceite de oliva'),
  ('aceite de coco','aceite de girasol'),
  ('aceite de coco','margarina vegana'),
  ('aceite de girasol','aceite vegetal'),
  ('aceite de girasol','manteca vegetal'),
  ('aceite de girasol','aceite de oliva'),
  ('aceite de girasol','aceite de coco'),
  ('aceite de girasol','margarina vegana'),
  ('aceite de oliva','aceite vegetal'),
  ('aceite de oliva','manteca vegetal'),
  ('aceite de oliva','aceite de coco'),
  ('aceite de oliva','aceite de girasol'),
  ('aceite de oliva','margarina vegana'),
  ('aceite vegetal','manteca vegetal'),
  ('aceite vegetal','aceite de oliva'),
  ('aceite vegetal','aceite de coco'),
  ('aceite vegetal','aceite de girasol'),
  ('aceite vegetal','margarina vegana'),
  ('agar agar','gelatina sin sabor'),
  ('agar agar','psyllium husk'),
  ('agar agar','goma xantana'),
  ('agar agar','almidon de papa'),
  ('agar agar','harina de coco'),
  ('aguacate','leche de soya'),
  ('aguacate','leche entera'),
  ('aguacate','leche de macadamia'),
  ('aguacate','leche de almendra'),
  ('aguacate','leche de avena'),
  ('algarroba en polvo','xilitol'),
  ('algarroba en polvo','eritritol'),
  ('algarroba en polvo','stevia'),
  ('algarroba en polvo','azucar de coco'),
  ('algarroba en polvo','azucar blanca'),
  ('almidon de maiz','harina integral'),
  ('almidon de maiz','tapioca'),
  ('almidon de maiz','harina de quinoa'),
  ('almidon de maiz','harina de garbanzo'),
  ('almidon de maiz','harina de trigo'),
  ('almidon de papa','tapioca'),
  ('almidon de papa','harina integral'),
  ('almidon de papa','almidon de maiz'),
  ('almidon de papa','agar agar'),
  ('almidon de papa','harina de quinoa'),
  ('aquafaba','yogur natural'),
  ('aquafaba','huevo'),
  ('aquafaba','gel de linaza'),
  ('aquafaba','gel de chia'),
  ('aquafaba','tofu sedoso'),
  ('avena','harina de avena'),
  ('avena','harina de trigo'),
  ('avena','semola'),
  ('avena','harina de maiz'),
  ('avena','harina de quinoa'),
  ('azucar blanca','azucar flor'),
  ('azucar blanca','stevia'),
  ('azucar blanca','panela'),
  ('azucar blanca','azucar morena'),
  ('azucar blanca','azucar de coco'),
  ('azucar de coco','panela'),
  ('azucar de coco','azucar morena'),
  ('azucar de coco','azucar blanca'),
  ('azucar de coco','azucar flor'),
  ('azucar de coco','stevia'),
  ('azucar flor','azucar blanca'),
  ('azucar flor','stevia'),
  ('azucar flor','panela'),
  ('azucar flor','azucar morena'),
  ('azucar flor','azucar de coco'),
  ('azucar morena','panela'),
  ('azucar morena','azucar blanca'),
  ('azucar morena','azucar flor'),
  ('azucar morena','azucar de coco'),
  ('azucar morena','miel'),
  ('bicarbonato de sodio','levadura seca'),
  ('bicarbonato de sodio','polvo de hornear'),
  ('bicarbonato de sodio','cremor tartaro'),
  ('bicarbonato de sodio','levadura fresca'),
  ('bicarbonato de sodio','buttermilk'),
  ('buttermilk','yogur vegano'),
  ('buttermilk','vinagre blanco'),
  ('buttermilk','yogur natural'),
  ('buttermilk','aquafaba'),
  ('buttermilk','crema agria'),
  ('cacao amargo','cacao en polvo'),
  ('cacao amargo','harina de maiz'),
  ('cacao amargo','sal'),
  ('cacao amargo','cafe soluble'),
  ('cacao amargo','avena'),
  ('cacao en polvo','cacao amargo'),
  ('cacao en polvo','harina de maiz'),
  ('cacao en polvo','sal'),
  ('cacao en polvo','cafe soluble'),
  ('cacao en polvo','avena'),
  ('cafe soluble','sal'),
  ('cafe soluble','canela'),
  ('cafe soluble','harina de maiz'),
  ('cafe soluble','harina de arroz'),
  ('cafe soluble','cacao en polvo'),
  ('canela','cafe soluble'),
  ('canela','sal'),
  ('canela','harina de maiz'),
  ('canela','harina de arroz'),
  ('canela','cacao en polvo'),
  ('chocolate blanco','chocolate cobertura'),
  ('chocolate blanco','xilitol'),
  ('chocolate blanco','eritritol'),
  ('chocolate blanco','stevia'),
  ('chocolate blanco','azucar blanca'),
  ('chocolate cobertura','chocolate blanco'),
  ('chocolate cobertura','xilitol'),
  ('chocolate cobertura','eritritol'),
  ('chocolate cobertura','stevia'),
  ('chocolate cobertura','azucar blanca'),
  ('crema','crema de coco'),
  ('crema','leche de coco'),
  ('crema','queso crema'),
  ('crema','crema agria'),
  ('crema','aguacate'),
  ('crema agria','aguacate'),
  ('crema agria','leche de macadamia'),
  ('crema agria','leche de coco'),
  ('crema agria','leche entera'),
  ('crema agria','leche de almendra'),
  ('crema de coco','crema'),
  ('crema de coco','leche de coco'),
  ('crema de coco','queso crema'),
  ('crema de coco','aguacate'),
  ('crema de coco','margarina vegana'),
  ('cremor tartaro','bicarbonato de sodio'),
  ('cremor tartaro','levadura seca'),
  ('cremor tartaro','polvo de hornear'),
  ('cremor tartaro','levadura fresca'),
  ('cremor tartaro','sal'),
  ('datiles molidos','miel'),
  ('datiles molidos','azucar morena'),
  ('datiles molidos','panela'),
  ('datiles molidos','azucar de coco'),
  ('datiles molidos','jarabe de maple'),
  ('eritritol','xilitol'),
  ('eritritol','stevia'),
  ('eritritol','azucar de coco'),
  ('eritritol','azucar blanca'),
  ('eritritol','azucar flor'),
  ('gel de chia','gel de linaza'),
  ('gel de chia','platano maduro'),
  ('gel de chia','tofu sedoso'),
  ('gel de chia','huevo'),
  ('gel de chia','pure de manzana'),
  ('gel de linaza','gel de chia'),
  ('gel de linaza','platano maduro'),
  ('gel de linaza','tofu sedoso'),
  ('gel de linaza','huevo'),
  ('gel de linaza','pure de manzana'),
  ('gelatina sin sabor','agar agar'),
  ('gelatina sin sabor','psyllium husk'),
  ('gelatina sin sabor','goma xantana'),
  ('gelatina sin sabor','almidon de papa'),
  ('gelatina sin sabor','harina de coco'),
  ('goma xantana','psyllium husk'),
  ('goma xantana','gelatina sin sabor'),
  ('goma xantana','agar agar'),
  ('goma xantana','almidon de papa'),
  ('goma xantana','harina de coco'),
  ('harina de almendra','mantequilla de mani'),
  ('harina de almendra','semillas de lino'),
  ('harina de almendra','nueces molidas'),
  ('harina de almendra','margarina vegana'),
  ('harina de almendra','mantequilla'),
  ('harina de arroz','harina de maiz'),
  ('harina de arroz','cafe soluble'),
  ('harina de arroz','sal'),
  ('harina de arroz','canela'),
  ('harina de arroz','semola'),
  ('harina de avena','avena'),
  ('harina de avena','harina de trigo'),
  ('harina de avena','semola'),
  ('harina de avena','harina de maiz'),
  ('harina de avena','harina de quinoa'),
  ('harina de coco','harina de garbanzo'),
  ('harina de coco','harina de quinoa'),
  ('harina de coco','almidon de papa'),
  ('harina de coco','agar agar'),
  ('harina de coco','gelatina sin sabor'),
  ('harina de garbanzo','harina de quinoa'),
  ('harina de garbanzo','almidon de maiz'),
  ('harina de garbanzo','harina integral'),
  ('harina de garbanzo','tapioca'),
  ('harina de garbanzo','harina de coco'),
  ('harina de maiz','harina de arroz'),
  ('harina de maiz','sal'),
  ('harina de maiz','cafe soluble'),
  ('harina de maiz','canela'),
  ('harina de maiz','cacao en polvo'),
  ('harina de quinoa','harina integral'),
  ('harina de quinoa','almidon de maiz'),
  ('harina de quinoa','tapioca'),
  ('harina de quinoa','harina de garbanzo'),
  ('harina de quinoa','avena'),
  ('harina de trigo','semola'),
  ('harina de trigo','harina de avena'),
  ('harina de trigo','avena'),
  ('harina de trigo','harina de arroz'),
  ('harina de trigo','almidon de maiz'),
  ('harina integral','almidon de maiz'),
  ('harina integral','tapioca'),
  ('harina integral','harina de quinoa'),
  ('harina integral','harina de garbanzo'),
  ('harina integral','harina de trigo'),
  ('huevo','gel de chia'),
  ('huevo','gel de linaza'),
  ('huevo','platano maduro'),
  ('huevo','aquafaba'),
  ('huevo','tofu sedoso'),
  ('jarabe de agave','leche condensada'),
  ('jarabe de agave','jarabe de maple'),
  ('jarabe de agave','stevia'),
  ('jarabe de agave','azucar flor'),
  ('jarabe de agave','azucar blanca'),
  ('jarabe de maple','jarabe de agave'),
  ('jarabe de maple','leche condensada'),
  ('jarabe de maple','miel'),
  ('jarabe de maple','datiles molidos'),
  ('jarabe de maple','azucar flor'),
  ('jugo de limon','vinagre blanco'),
  ('jugo de limon','leche de arroz'),
  ('jugo de limon','leche de avena'),
  ('jugo de limon','leche descremada'),
  ('jugo de limon','leche de almendra'),
  ('leche condensada','jarabe de agave'),
  ('leche condensada','miel'),
  ('leche condensada','azucar flor'),
  ('leche condensada','jarabe de maple'),
  ('leche condensada','azucar blanca'),
  ('leche de almendra','leche de macadamia'),
  ('leche de almendra','leche de avena'),
  ('leche de almendra','leche descremada'),
  ('leche de almendra','leche de soya'),
  ('leche de almendra','leche entera'),
  ('leche de arroz','leche de avena'),
  ('leche de arroz','leche descremada'),
  ('leche de arroz','leche de macadamia'),
  ('leche de arroz','leche de almendra'),
  ('leche de arroz','jugo de limon'),
  ('leche de avena','leche descremada'),
  ('leche de avena','leche de almendra'),
  ('leche de avena','leche de macadamia'),
  ('leche de avena','leche de arroz'),
  ('leche de avena','leche entera'),
  ('leche de coco','crema'),
  ('leche de coco','crema de coco'),
  ('leche de coco','aguacate'),
  ('leche de coco','leche de macadamia'),
  ('leche de coco','crema agria'),
  ('leche de macadamia','leche de almendra'),
  ('leche de macadamia','leche de avena'),
  ('leche de macadamia','leche descremada'),
  ('leche de macadamia','leche entera'),
  ('leche de macadamia','leche de soya'),
  ('leche de soya','leche entera'),
  ('leche de soya','leche de almendra'),
  ('leche de soya','leche de macadamia'),
  ('leche de soya','leche de avena'),
  ('leche de soya','leche descremada'),
  ('leche descremada','leche de avena'),
  ('leche descremada','leche de almendra'),
  ('leche descremada','leche de macadamia'),
  ('leche descremada','leche de arroz'),
  ('leche descremada','leche entera'),
  ('leche entera','leche de soya'),
  ('leche entera','leche de almendra'),
  ('leche entera','leche de macadamia'),
  ('leche entera','leche de avena'),
  ('leche entera','leche descremada'),
  ('levadura fresca','polvo de hornear'),
  ('levadura fresca','levadura seca'),
  ('levadura fresca','bicarbonato de sodio'),
  ('levadura fresca','cremor tartaro'),
  ('levadura fresca','buttermilk'),
  ('levadura seca','polvo de hornear'),
  ('levadura seca','bicarbonato de sodio'),
  ('levadura seca','levadura fresca'),
  ('levadura seca','cremor tartaro'),
  ('levadura seca','buttermilk'),
  ('manteca vegetal','aceite vegetal'),
  ('manteca vegetal','aceite de oliva'),
  ('manteca vegetal','aceite de coco'),
  ('manteca vegetal','aceite de girasol'),
  ('manteca vegetal','margarina vegana'),
  ('mantequilla','margarina vegana'),
  ('mantequilla','aceite vegetal'),
  ('mantequilla','aceite de coco'),
  ('mantequilla','aceite de girasol'),
  ('mantequilla','manteca vegetal'),
  ('mantequilla de mani','harina de almendra'),
  ('mantequilla de mani','semillas de lino'),
  ('mantequilla de mani','nueces molidas'),
  ('mantequilla de mani','margarina vegana'),
  ('mantequilla de mani','mantequilla'),
  ('margarina vegana','mantequilla'),
  ('margarina vegana','aceite vegetal'),
  ('margarina vegana','aceite de coco'),
  ('margarina vegana','aceite de girasol'),
  ('margarina vegana','manteca vegetal'),
  ('miel','azucar morena'),
  ('miel','panela'),
  ('miel','azucar flor'),
  ('miel','azucar blanca'),
  ('miel','datiles molidos'),
  ('nueces molidas','margarina vegana'),
  ('nueces molidas','mantequilla'),
  ('nueces molidas','aceite vegetal'),
  ('nueces molidas','aceite de girasol'),
  ('nueces molidas','manteca vegetal'),
  ('panela','azucar morena'),
  ('panela','azucar de coco'),
  ('panela','azucar blanca'),
  ('panela','azucar flor'),
  ('panela','miel'),
  ('platano maduro','gel de chia'),
  ('platano maduro','gel de linaza'),
  ('platano maduro','pure de manzana'),
  ('platano maduro','tofu sedoso'),
  ('platano maduro','huevo'),
  ('polvo de hornear','levadura seca'),
  ('polvo de hornear','bicarbonato de sodio'),
  ('polvo de hornear','levadura fresca'),
  ('polvo de hornear','cremor tartaro'),
  ('polvo de hornear','buttermilk'),
  ('psyllium husk','goma xantana'),
  ('psyllium husk','gelatina sin sabor'),
  ('psyllium husk','agar agar'),
  ('psyllium husk','almidon de papa'),
  ('psyllium husk','harina de coco'),
  ('pure de calabaza','pure de zapallo'),
  ('pure de calabaza','pure de remolacha'),
  ('pure de calabaza','tofu sedoso'),
  ('pure de calabaza','pure de manzana'),
  ('pure de calabaza','yogur natural'),
  ('pure de manzana','tofu sedoso'),
  ('pure de manzana','pure de zapallo'),
  ('pure de manzana','pure de calabaza'),
  ('pure de manzana','platano maduro'),
  ('pure de manzana','gel de linaza'),
  ('pure de remolacha','pure de zapallo'),
  ('pure de remolacha','pure de calabaza'),
  ('pure de remolacha','yogur vegano'),
  ('pure de remolacha','tofu sedoso'),
  ('pure de remolacha','pure de manzana'),
  ('pure de zapallo','pure de calabaza'),
  ('pure de zapallo','pure de remolacha'),
  ('pure de zapallo','tofu sedoso'),
  ('pure de zapallo','pure de manzana'),
  ('pure de zapallo','yogur natural'),
  ('queso crema','crema'),
  ('queso crema','crema de coco'),
  ('queso crema','aguacate'),
  ('queso crema','leche de coco'),
  ('queso crema','crema agria'),
  ('sal','cafe soluble'),
  ('sal','canela'),
  ('sal','harina de maiz'),
  ('sal','harina de arroz'),
  ('sal','cacao en polvo'),
  ('semillas de lino','harina de almendra'),
  ('semillas de lino','mantequilla de mani'),
  ('semillas de lino','nueces molidas'),
  ('semillas de lino','margarina vegana'),
  ('semillas de lino','mantequilla'),
  ('semola','harina de trigo'),
  ('semola','avena'),
  ('semola','harina de avena'),
  ('semola','harina de arroz'),
  ('semola','almidon de maiz'),
  ('stevia','eritritol'),
  ('stevia','xilitol'),
  ('stevia','azucar flor'),
  ('stevia','azucar blanca'),
  ('stevia','azucar de coco'),
  ('tapioca','almidon de maiz'),
  ('tapioca','harina integral'),
  ('tapioca','harina de quinoa'),
  ('tapioca','almidon de papa'),
  ('tapioca','harina de garbanzo'),
  ('tofu sedoso','pure de manzana'),
  ('tofu sedoso','pure de zapallo'),
  ('tofu sedoso','pure de calabaza'),
  ('tofu sedoso','gel de linaza'),
  ('tofu sedoso','gel de chia'),
  ('vainilla extracto','leche de arroz'),
  ('vainilla extracto','jugo de limon'),
  ('vainilla extracto','leche descremada'),
  ('vainilla extracto','leche de avena'),
  ('vainilla extracto','leche de almendra'),
  ('vinagre blanco','jugo de limon'),
  ('vinagre blanco','leche de arroz'),
  ('vinagre blanco','leche de almendra'),
  ('vinagre blanco','leche de macadamia'),
  ('vinagre blanco','leche de avena'),
  ('xilitol','eritritol'),
  ('xilitol','stevia'),
  ('xilitol','azucar de coco'),
  ('xilitol','azucar blanca'),
  ('xilitol','azucar flor'),
  ('yogur natural','yogur vegano'),
  ('yogur natural','aquafaba'),
  ('yogur natural','pure de zapallo'),
  ('yogur natural','pure de calabaza'),
  ('yogur natural','tofu sedoso'),
  ('yogur vegano','yogur natural'),
  ('yogur vegano','pure de remolacha'),
  ('yogur vegano','pure de zapallo'),
  ('yogur vegano','pure de calabaza'),
  ('yogur vegano','tofu sedoso')
)
SELECT e.o AS original, e.s AS sustituto,
       (SELECT COUNT(*) FROM ingredients WHERE name = e.o) AS filas_original,
       (SELECT COUNT(*) FROM ingredients WHERE name = e.s) AS filas_sustituto
FROM esperado e
WHERE NOT EXISTS (
  SELECT 1 FROM substitutes x
  JOIN ingredients a ON a.id = x.original_id
  JOIN ingredients b ON b.id = x.substitute_id
  WHERE a.name = e.o AND b.name = e.s)
ORDER BY 1, 2;

-- B) Totales de control
SELECT (SELECT COUNT(*) FROM substitutes) AS sustitutos_en_base,
       (SELECT COUNT(*) FROM ingredients) AS ingredientes_en_base;
